#Колосс
- type: entity
  id: MobLavaLandColossusBOSS
  parent: BaseMobLavaLand
  suffix: LavaLand
  categories: [ HideSpawnMenu ]
  name: магматитовый колосс
  description: Огромный каменный танк.
  components:
  - type: Tag
    tags:
    - CannotSuicide
    - FootstepSound
    - LavaMob
  - type: Sprite
    sprite: Adventure/Roles/LavaLand/mobs/BOSSES/colossus.rsi
  - type: MovementSpeedModifier
    baseWalkSpeed : 2.0
    baseSprintSpeed : 2.0
  - type: MobThresholds
    thresholds:
      0: Alive
      3500: Dead
  - type: MeleeWeapon
    soundHit:
      path: "/Audio/Weapons/smash.ogg"
    angle: 0
    attackRate: 0.75
    animation: WeaponArcPunch
    damage:
      types:
        Blunt: 20
        Heat: 20
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeCircle
          radius: 0.35
        density: 10000
        mask:
        - MobMask
        layer:
        - MobLayer
  - type: Butcherable
    butcherDelay: 30
    spawned:
    - id: DiamondOre1
      amount: 5
    - id: OreEmerald1
      amount: 2
    - id: OreSapphire1
      amount: 2
    - id: OreTopaz1
      amount: 2
    - id: GoldOre1
      amount: 2
    - id: Coal1
      amount: 10
    - id: MaterialMagmatite1
      amount: 10
  - type: FootstepModifier
    footstepSoundCollection:
      collection: FootstepThud
  - type: PointLight
    radius: 4
    energy: 1.5
    color: "#f2511e"
  - type: Gun
    fireRate: 1
    selectedMode: SemiAuto
    showExamineText: false
    availableModes:
    - SemiAuto
    soundGunshot: null
  - type: BatterySelfRecharger
    autoRecharge: true
    autoRechargeRate: 20
  - type: Battery
    maxCharge: 60
    startingCharge: 60
  - type: ProjectileBatteryAmmoProvider
    proto: MobLavaCrabLavaLand
    fireCost: 60
  - type: HTN
    rootTask:
      task: SimpleMeleeRangedHostileCompoundAudioTrigger
    blackboard:
      VisionRadius: !type:Single
        9
      AggroVisionRadius: !type:Single
        9
      SoundTargetInLOS: !type:SoundPathSpecifier
        path: /Audio/Adventure/LavaLand/StoneMagma.ogg
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageGroupTrigger
        damageGroup: Brute
        damage: 6000
  - type: AmbientSound
    range: 10
    sound:
      path: /Audio/Adventure/LavaLand/Magma.ogg
  - type: ExplosionResistance
    damageCoefficient: 0.0

# Спавн
- type: entity
  id: MobSpawnLavaColossus
  categories: [ HideSpawnMenu ]
  name: магматитовая скала
  components:
  - type: Transform
    anchored: True
  - type: InteractionOutline
  - type: Physics
    bodyType: Static
  - type: Sprite
    noRot: true
    sprite: Adventure/Roles/LavaLand/mobs/BOSSES/colossus.rsi
    layers:
    - state: spawn
    - state: spawn_light
      shader: unshaded
  - type: Fixtures
    fixtures:
      portalFixture:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.48,-0.48,0.48,0.48"
        mask:
        - FullTileMask
        layer:
        - WallLayer
        hard: false
  - type: TimedDespawn
    lifetime: 5.0
  - type: SpawnOnDespawn
    prototype: MobLavaLandColossusBOSS
  - type: PointLight
    radius: 4
    energy: 1.5
    color: "#f2511e"
  - type: EmitSoundOnSpawn
    sound:
      path: /Audio/Adventure/LavaLand/ColossusSpawn.ogg

- type: entity
  id: MobLavaLandColossusSleep
  parent: BaseStructure
  suffix: Спавн колосса LavaLand
  name: магматитовая скала
  description: Огромная сказал магматита.
  components:
    - type: Sprite
      sprite: Adventure/Roles/LavaLand/mobs/BOSSES/colossus.rsi
      layers:
      - state: sleep
      - state: sleep_light
        shader: unshaded
      noRot: true
    - type: Physics
      bodyType: Static
    - type: Fixtures
      fixtures:
        fix1:
          shape:
            !type:PhysShapeCircle
            radius: 0.60
          density: 10000
          mask:
            - MachineMask
          layer:
            - MidImpassable
            - LowImpassable
            - BulletImpassable
            - Opaque
    - type: PointLight
      radius: 4
      energy: 1.5
      color: "#f2511e"
    - type: Damageable
      damageContainer: StructuralInorganic
      damageModifierSet: Glass
    - type: Destructible
      thresholds:
        - trigger:
            !type:DamageTrigger
            damage: 2
          behaviors:
            - !type:SpawnEntitiesBehavior
              spawn:
                MobSpawnLavaColossus:
                  min: 1
                  max: 1
            - !type:DoActsBehavior
              acts: [ "Destruction" ]
    - type: AmbientSound
      range: 10
      sound:
        path: /Audio/Adventure/LavaLand/Magma.ogg
