- type: entity
  name: отбойный молот
  parent: BaseItem
  id: MiningJackhammer
  suffix: LavaLand
  description: Мощный инструмент, используемый для быстрого бурения горных пород.
  components:
  - type: Item
    size: Large
    storedRotation: -90
  - type: Tag
    tags:
    - Pickaxe
  - type: Sprite
    sprite: Adventure/Roles/LavaLand/Equipment/Jackhammer.rsi
    state: Jackhammer
  - type: MultiHandedItem
  - type: MeleeWeapon
    autoAttack: true
    angle: 0
    wideAnimationRotation: -90
    soundHit:
      path: "/Audio/Adventure/LavaLand/Jackhammer.ogg"
    attackRate: 5
    damage:
      groups:
        Brute: 15
      types:
        Structural: 35