#Жнец-рабочий
- type: entity
  name: жнец-рабочий
  suffix: BORK (HungerSwarm)
  description: Им движет только одно - сожрать вас.
  parent: BaseMobInsectReaper
  id: MobInsectReaper
  components:
  - type: Sprite
    drawdepth: Mobs
    sprite: Adventure/Roles/Hungry_Swarm/reaper.rsi
    layers:
    - map: ["enum.DamageStateVisualLayers.Base"]
      state: alive
  - type: MovementSpeedModifier
    baseSprintSpeed: 4.5
    baseWalkSpeed : 2.5
  - type: GhostRole
    allowMovement: true
    allowSpeech: true
    makeSentient: true
    name: Рабочий жнец улья
    description: Стройте и укрепляйте улей.
    rules: Вы [color=red][bold]Командный антагонист[/bold][/color], в команде с другими членами улья.
    raffle:
      settings: short
  - type: PointLight
    radius: 2
    energy: 3
    color: "#d2af52"
  - type: AutoImplant
    implants:
    - ActionHungerSwarmWallImplant  
    - ActionHungerSwarmWallReinforseImplant
    - ActionHungerSwarmDoorImplant
    - ActionHungerSwarmWebLightImplant
    - HungerSwarmImplant
  - type: Reform
    actionPrototype: ReaperQuardianEvolutionAction
    reformTime: 20
    popupText: Вы начинаете меняться
    reformPrototype: MobInsectReaperGuardian

#Жнец-страж
- type: entity
  name: жнец-страж
  suffix: BORK (HungerSwarm)
  description: Им движет только одно - сожрать вас.
  parent: BaseMobInsectReaper
  id: MobInsectReaperGuardian
  components:
  - type: Sprite
    drawdepth: Mobs
    sprite: Adventure/Roles/Hungry_Swarm/guardian.rsi
    layers:
    - map: ["enum.DamageStateVisualLayers.Base"]
      state: alive
  - type: MovementSpeedModifier
    baseSprintSpeed: 5.5
    baseWalkSpeed : 3.5
  - type: GhostRole
    allowMovement: true
    allowSpeech: true
    makeSentient: true
    name: Страж улья
    description: Защищайте улей и его обитателей.
    rules: Вы [color=red][bold]Командный антагонист[/bold][/color], в команде с другими членами улья.
    raffle:
      settings: short
  - type: PointLight
    radius: 2
    energy: 2
    color: "#d2af52"
  - type: AutoImplant
    implants:
    - ActionHungerSwarmWebStickyImplant
    - HungerSwarmImplant
  - type: SolutionContainerManager
    solutions:
      melee:
        reagents:
        - ReagentId: ReaperPoison
          Quantity: 100
  - type: SolutionRegeneration
    solution: melee
    generated:
      reagents:
      - ReagentId: ReaperPoison
        Quantity: 1
  - type: MeleeChemicalInjector
    solution: melee
    transferAmount: 2
  - type: Tag
    tags:
    - FootstepSound
    - HungerSwarm
    - HungerSwarmGuardian

#Жнец-хранитель
- type: entity
  name: жнец-хранитель
  suffix: BORK (HungerSwarm)
  description: Им движет только одно - сожрать вас.
  parent: MobInsectReaperGuardian
  id: MobInsectReaperKeeper
  components:
  - type: MeleeWeapon
    altDisarm: false
    angle: 0
    damage:
      types:
        Piercing: 10
        Structural: 30
  - type: MobThresholds
    thresholds:
      0: Alive
      150: Dead
  - type: Sprite
    drawdepth: Mobs
    sprite: Adventure/Roles/Hungry_Swarm/keeper.rsi
    layers:
    - map: ["enum.DamageStateVisualLayers.Base"]
      state: alive
  - type: GhostRole
    allowMovement: true
    allowSpeech: true
    makeSentient: true
    name: Хранитель улья
    description: Защищайте королеву.
    rules: Вы [color=red][bold]Командный антагонист[/bold][/color], в команде с другими членами улья.
    raffle:
      settings: short
  - type: AutoImplant
    implants:
    - HungerSwarmImplant
  - type: Tag
    tags:
    - FootstepSound
    - HungerSwarm

#Королева
- type: entity
  name: матка жнецов
  suffix: BORK (HungerSwarm)
  description: Им движет только одно - сожрать вас.
  parent: BaseMobInsectReaper
  id: MobInsectReaperQueen
  components:
  - type: Sprite
    drawdepth: Mobs
    sprite: Adventure/Roles/Hungry_Swarm/queen.rsi
    layers:
    - map: ["enum.DamageStateVisualLayers.Base"]
      state: alive
  - type: MobThresholds
    thresholds:
      0: Alive
      300: Dead
  - type: SlowOnDamage
    speedModifierThresholds:
      200: 0.7
  - type: MovementSpeedModifier
    baseSprintSpeed: 4.5
    baseWalkSpeed : 2.5
  - type: GhostRole
    allowMovement: true
    allowSpeech: true
    makeSentient: true
    name: Матка улья
    description: Размножайтесь и поедайте всё, что найдёте.
    rules: Вы [color=red][bold]Командный антагонист[/bold][/color], в команде с другими членами улья.
    raffle:
      settings: short
  - type: Butcherable
    spawned:
      - id: FoodMeat
        amount: 3
  - type: EggLayer
    hungerUsage: 10
    eggLayAction: ActionHungerSwarmLayEgg
    eggLaySound: !type:SoundPathSpecifier
      path: /Audio/Adventure/Hungry_Swarm/insect_dead.ogg
    eggSpawn:
    - id: InsectReaperEgg
  - type: PointLight
    radius: 2
    energy: 2
    color: "#e6a10f"
  - type: MeleeWeapon
    altDisarm: false
    angle: 0
    damage:
      types:
        Piercing: 20
        Structural: 30
  - type: AutoImplant
    implants:
    - ActionHungerSwarmWallImplant  
    - ActionHungerSwarmDoorImplant
    - HungerSwarmImplant
    - ActionForceKeeperImplant
  - type: HungerSwarmQueen

- type: soundCollection
  id: ReaperFly
  files:
  - /Audio/Adventure/Hungry_Swarm/insect_fly1.ogg
  - /Audio/Adventure/Hungry_Swarm/insect_fly2.ogg
  - /Audio/Adventure/Hungry_Swarm/insect_fly3.ogg

#Личинка жнеца
- type: entity
  name: личинка жнеца
  suffix: BORK (HungerSwarm)
  description: Им движет только одно - сожрать вас.
  parent: BaseMobInsectSwarm
  id: MobInsectLarva
  components:
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeCircle
          radius: 0.25
        density: 30
        mask:
        - SmallMobMask
        layer:
        - SmallMobLayer
  - type: Sprite
    drawdepth: Mobs
    sprite: Adventure/Roles/Hungry_Swarm/larva.rsi
    layers:
    - map: ["enum.DamageStateVisualLayers.Base"]
      state: alive
  - type: MobThresholds
    thresholds:
      0: Alive
      50: Dead
  - type: SlowOnDamage
    speedModifierThresholds:
      70: 0.7
  - type: MovementSpeedModifier
    baseSprintSpeed: 2
    baseWalkSpeed : 2.5
  - type: GhostRole
    allowMovement: true
    allowSpeech: true
    makeSentient: true
    name: Личинка жнеца
    description: Дождитесь взросления и помогите рою выжить.
    rules: Вы [color=red][bold]Командный антагонист[/bold][/color], в команде с другими членами улья.
    raffle:
      settings: short
  - type: GhostTakeoverAvailable
  - type: Butcherable
    spawned:
      - id: FoodMeat
        amount: 1
  - type: FootstepModifier
    footstepSoundCollection:
      collection: LarvaRun
      params: 
        volume: -10
  - type: Reform
    actionPrototype: ReaperEvolutionAction
    reformTime: 20
    popupText: Вы начинаете окукливаться и отращивать крылья
    reformPrototype: MobInsectReaper
  - type: AutoImplant
    implants:
    - HungerSwarmImplant

- type: soundCollection
  id: LarvaRun
  files:
  - /Audio/Adventure/Hungry_Swarm/larva_run1.ogg
  - /Audio/Adventure/Hungry_Swarm/larva_run2.ogg

#яйца 
- type: entity
  id: InsectReaperEgg
  parent: BaseItem
  description: Там что-то швелится.
  name: яйцо жнеца
  suffix: BORK (HungerSwarm)
  components:
  - type: Item
    size: Huge
  - type: Damageable
    damageContainer: Biological
  - type: Sprite
    sprite: Adventure/Roles/Hungry_Swarm/other.rsi
    state: egg
  - type: Icon
    sprite: Adventure/Roles/Hungry_Swarm/other.rsi
    state: egg
  - type: Timer
  - type: TimedSpawner
    prototypes:
    - MobInsectLarva
    intervalSeconds: 120
    minimumEntitiesSpawned: 1
    maximumEntitiesSpawned: 1
  - type: TimedDespawn
    lifetime: 121
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 100
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: desecration
      - !type:SpillBehavior
        solution: food
      - !type:SpawnEntitiesBehavior
        spawn:
          MobInsectLarva:
            min: 1
            max: 1
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: DamageOnHighSpeedImpact
    minimumSpeed: 0.1
    damage:
      types:
        Blunt: 1

#жало
- type: entity
  id: BulletReaperSting
  name: жало жнеца
  parent: BaseBullet
  noSpawn: true
  components:
    - type: Sprite
      noRot: false
      sprite: Adventure/Roles/Hungry_Swarm/other.rsi
      layers:
        - state: sting
    - type: EmitSoundOnSpawn
      sound:
        path: /Audio/Adventure/Hungry_Swarm/insect_attack.ogg
    - type: Projectile
      impactEffect: BulletImpactEffectKinetic
      damage:
        types:
          Slash: 5
          Piercing: 5

- type: entity
  noSpawn: true
  id: ReaperGun
  components:
  - type: RechargeBasicEntityAmmo
    rechargeCooldown: 5
  - type: BasicEntityAmmoProvider
    proto: BulletReaperSting
    capacity: 1
    count: 1
  - type: Gun
    soundGunshot:
      path: /Audio/Adventure/Hungry_Swarm/insect_attack.ogg
    projectileSpeed: 10

# создания хранителя
- type: entity
  id: ProjectilePolyboltHungerSwarmKeeper
  parent: ProjectilePolyboltBase
  name: феромоны хранителя
  categories: [ HideSpawnMenu ]
  components:
  - type: Sprite
    sprite: Adventure/Roles/Hungry_Swarm/other.rsi
    layers:
    - state: buff
  - type: Projectile
    damage:
      types:
        Poison: 0
  - type: PolymorphOnCollide
    polymorph: MobInsectReaperKeeperPolymorph
    whitelist:
      tags:
      - HungerSwarmGuardian

- type: polymorph
  id: MobInsectReaperKeeperPolymorph
  configuration:
    entity: MobInsectReaperKeeper
    forced: true
    inventory: Transfer
    transferName: false
    transferDamage: true
    revertOnCrit: false
    revertOnDeath: false