#магматит
- type: entity
  parent: MaterialBase
  id: MaterialMagmatite
  name: магматит
  description: Невероятно крепкий материал, способный выдерживать высокие температуры.
  suffix: LavaLand
  components:
  - type: Sprite
    sprite: Adventure/Roles/LavaLand/materials/Magma.rsi
    layers:
    - state: magmatite
    - state: magmatite_light
      shader: unshaded
  - type: Appearance
  - type: Stack
    stackType: Magmatite
  - type: Item
    size: Large
  - type: PointLight
    radius: 2
    energy: 1.5
    color: "#f2511e"
  - type: Material
  - type: PhysicalComposition
    materialComposition:
      Magmatite: 100
  - type: DamageOnInteract
    damage:
      types:
        Heat: 5
    popupText: "Магматит обжигает ваши руки."
  - type: Damageable
    damageContainer: StructuralInorganic
    damageModifierSet: Rock
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 120
      behaviors:
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
      - !type:PlaySoundBehavior
        sound:
          path: /Audio/Effects/break_stone.ogg
          params:
            volume: -6
      - !type:SpawnEntitiesBehavior
        spawn:
          MaterialMagmatiteFragment1:
            min: 10
            max: 10
      - !type:DoActsBehavior
        acts: [ "Destruction" ]

- type: entity
  parent: MaterialMagmatite
  id: MaterialMagmatite1
  suffix: 1
  components:
  - type: Stack
    count: 1
  - type: Construction
    graph: Magmatite
    node: done

- type: stack
  id: Magmatite
  name: магматит
  icon: { sprite: /Textures/Adventure/Roles/LavaLand/materials/Magma.rsi, state: magmatite }
  spawn: MaterialMagmatite1
  maxCount: 30

- type: material
  id: Magmatite
  name: магматит
  unit: materials-unit-piece
  icon: { sprite: Adventure/Roles/LavaLand/materials/Magma.rsi, state: magmatite }
  color: "#e64e04"
  price: 10

#осколок магматита
- type: entity
  parent: MaterialBase
  id: MaterialMagmatiteFragment
  name: осколок магматита
  description: Невероятно крепкий материал, способный выдерживать высокие температуры.
  suffix: LavaLand
  components:
  - type: Sprite
    sprite: Adventure/Roles/LavaLand/materials/Magma.rsi
    layers:
    - state: fragment
    - state: fragment_light
      shader: unshaded
  - type: Appearance
  - type: Stack
    stackType: MagmatiteFragment
  - type: Item
    size: Normal
  - type: Tag
    tags:
    - Ore
  - type: PointLight
    radius: 2
    energy: 1.5
    color: "#f2511e"
  - type: Material
  - type: PhysicalComposition
    materialComposition:
      MagmatiteFragment: 100
  - type: DamageOnInteract
    damage:
      types:
        Heat: 1
    popupText: "Магматит обжигает ваши руки."
  - type: Extractable
    grindableSolutionName: magma
  - type: SolutionContainerManager
    solutions:
      magma:
        reagents:
        - ReagentId: Charcoal
          Quantity: 3
        - ReagentId: Gold
          Quantity: 1
        - ReagentId: Iron
          Quantity: 1

- type: entity
  parent: MaterialMagmatiteFragment
  id: MaterialMagmatiteFragment1
  suffix: 1
  components:
  - type: Stack
    count: 1

- type: stack
  id: MagmatiteFragment
  name: осколок магматита
  icon: { sprite: /Textures/Adventure/Roles/LavaLand/materials/Magma.rsi, state: fragment }
  spawn: MaterialMagmatiteFragment1
  maxCount: 30

- type: material
  id: MagmatiteFragment
  stackEntity: MaterialMagmatiteFragment1
  name: магматит
  unit: materials-unit-piece
  icon: { sprite: Adventure/Roles/LavaLand/materials/Magma.rsi, state: fragment }
  color: "#e64e04"
  price: 5

#крафт магматита
- type: constructionGraph
  id: Magmatite
  start: start
  graph:
  - node: start
    edges:
    - to: done
      steps:
      - material: MagmatiteFragment
        amount: 10
        doAfter: 10
  - node: done
    entity: MaterialMagmatite1

- type: construction
  name: магматит
  id: Magmatite
  graph: Magmatite
  startNode: start
  targetNode: done
  category: construction-category-misc
  objectType: Item
  description: Невероятно крепкий материал, способный выдерживать высокие температуры.
  icon:
    sprite: Adventure/Roles/LavaLand/materials/Magma.rsi
    state: magmatite

#Залежи 
- type: entity
  id: WallRockBasaltMagmatite
  name: базальт
  parent: WallRockBasalt
  description: Рудная жила, богатая магматитом.
  suffix: Магматит LavaLand
  components:
    - type: OreVein
      oreChance: 1.0
      currentOre: OreMagmatiteFragment
    - type: Sprite
      layers:
        - state: rock_wall
        - map: [ "enum.EdgeLayer.South" ]
          state: rock_wall_south
        - map: [ "enum.EdgeLayer.East" ]
          state: rock_wall_east
        - map: [ "enum.EdgeLayer.North" ]
          state: rock_wall_north
        - map: [ "enum.EdgeLayer.West" ]
          state: rock_wall_west
        - state: rock_magma
          map: [ "enum.MiningScannerVisualLayers.Overlay" ]
    - type: PointLight
      radius: 2
      energy: 1.5
      color: "#f2511e"

- type: ore
  id: OreMagmatiteFragment
  oreEntity: MaterialMagmatiteFragment1
  minOreYield: 1
  maxOreYield: 2

- type: entity
  id: WallRockBasaltMagmatiteCrab
  parent: WallRockBasaltMagmatite
  suffix: Магматититовый краб LavaLand
  components:
    - type: OreVein
      oreChance: 1.0
      currentOre: OreLavaCrab

- type: ore
  id: OreLavaCrab
  oreEntity: MobLavaCrabLavaLand

#обработанный магматит
- type: entity
  parent: MaterialBase
  id: ProcessedMagmatite
  name: обработанный магматит
  description: Неверится, что это всего застывшая лава.
  suffix: LavaLand
  components:
  - type: Sprite
    sprite: Adventure/Roles/LavaLand/materials/gems.rsi
    layers:
    - state: processed_magmatite
      shader: unshaded
  - type: Appearance
  - type: Stack
    stackType: ProcessedMagmatite
  - type: PointLight
    radius: 2
    energy: 1.5
    color: "#f2511e"
  - type: Material
  - type: PhysicalComposition
    materialComposition:
      ProcessedMagmatite: 100

- type: latheRecipe
  id: ProcessedMagmatite
  result: ProcessedMagmatite1
  completetime: 0
  materials:
    MagmatiteFragment: 1000

- type: entity
  parent: ProcessedMagmatite
  id: ProcessedMagmatite1
  suffix: 1
  components:
  - type: Stack
    count: 1

- type: stack
  id: ProcessedMagmatite
  name: осколок магматита
  icon: { sprite: /Textures/Adventure/Roles/LavaLand/materials/gems.rsi, state: processed_magmatite }
  spawn: ProcessedMagmatite1
  maxCount: 30

- type: material
  id: ProcessedMagmatite
  name: магматит
  unit: materials-unit-piece
  icon: { sprite: Adventure/Roles/LavaLand/materials/gems.rsi, state: processed_magmatite }
  color: "#e64e04"
  price: 25