- type: entity
  id: BaseMobLavaLand
  parent: BaseMobAsteroid
  abstract: true
  components:
  - type: Sprite
    sprite: Adventure/Roles/LavaLand/mobs/goliath.rsi
    layers:
    - map: [ "enum.DamageStateVisualLayers.Base" ]
      state: alive
    - map: [ "enum.DamageStateVisualLayers.BaseUnshaded" ]
      state: light_alive
      shader: unshaded
  - type: DamageStateVisuals
    states:
      Alive:
        Base: alive
        BaseUnshaded: light_alive
      Dead:
        Base: dead
        BaseUnshaded: light_dead
  - type: Flammable
    fireSpread: false
    canResistFire: false
    damage:
      types:
        Heat: 0.0
  - type: ZombieImmune
  - type: NpcFactionMember
    factions:
    - SimpleHostile
  - type: Tag
    tags:
    - CannotSuicide
    - LavaMob
  - type: NoSlip
  - type: Temperature
    heatDamageThreshold: 100273,15 
    specificHeat: 10000
  - type: ExplosionResistance
    damageCoefficient: 0.5
  - type: StatusEffects
    allowed:
    - SlowedDown
    - Stutter
    - Electrocution
    - TemporaryBlindness
    - RadiationProtection
    - Drowsiness
    - Adrenaline

- type: Tag
  id: LavaMob

#Голиаф
- type: entity
  id: MobLavaLandGoliath
  parent: BaseMobLavaLand
  suffix: LavaLand
  name: магмавый голиаф
  description: Массивное чудовище, использующее свои длинные щупальца для ловли добычи. Не рекомендуется угрожать им ни при каких условиях.
  components:
  - type: Sprite
    sprite: Adventure/Roles/LavaLand/mobs/goliath.rsi
  - type: MovementSpeedModifier
    baseWalkSpeed : 2.50
    baseSprintSpeed : 2.50
  - type: MobThresholds
    thresholds:
      0: Alive
      200: Dead
  - type: MeleeWeapon
    soundHit:
      path: "/Audio/Weapons/smash.ogg"
    angle: 0
    attackRate: 0.75
    animation: WeaponArcPunch
    damage:
      types:
        Slash: 10
        Piercing: 5
  - type: HTN
    rootTask:
      task: GoliathCompound
    blackboard:
      VisionRadius: !type:Single
        6
      AggroVisionRadius: !type:Single
        10
  - type: NPCUseActionOnTarget
    actionId: ActionGoliathTentacle
  - type: Butcherable
    spawned:
    - id: FoodMeatGoliath
      amount: 3
    - id: MaterialGoliathHide1
      amount: 3
    - id: MaterialMagmatiteFragment1
      amount: 3
  - type: Tag
    tags:
    - CannotSuicide
    - FootstepSound  
    - LavaMob
  - type: PointLight
    radius: 2
    energy: 1.5
    color: "#f2511e"

#Голиаф Древний
- type: entity
  id: MobLavaLandGoliathAncient
  parent: MobLavaLandGoliath
  suffix: LavaLand
  name: древний магмавый голиаф
  components:
  - type: Sprite
    sprite: Adventure/Roles/LavaLand/mobs/old_goliath.rsi
  - type: MovementSpeedModifier
    baseWalkSpeed : 2.0
    baseSprintSpeed : 2.0
  - type: MobThresholds
    thresholds:
      0: Alive
      400: Dead
  - type: MeleeWeapon
    soundHit:
      path: "/Audio/Weapons/smash.ogg"
    angle: 0
    attackRate: 0.75
    animation: WeaponArcPunch
    damage:
      types:
        Slash: 15
        Piercing: 5
  - type: Butcherable
    spawned:
    - id: FoodMeatGoliath
      amount: 6
    - id: MaterialGoliathHide1
      amount: 6
    - id: MaterialMagmatite1
      amount: 1
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageGroupTrigger
        damageGroup: Brute
        damage: 6000

# наблюдатель
- type: entity
  id: MobWatcherLavaLandFire
  parent: [ BaseMobLavaLand, MobWatcherBase ]
  name: наблюдатель за огнём
  suffix: LavaLand
  description: Смотрит и поджигает.
  components:
  - type: Sprite
    sprite: Adventure/Roles/LavaLand/mobs/watcher.rsi
  - type: Butcherable
    spawned:
    - id: DiamondOre1
      amount: 5
  - type: MobThresholds
    thresholds:
      0: Alive
      75: Dead
  - type: MovementSpeedModifier
    baseWalkSpeed: 4
    baseSprintSpeed: 4
  - type: ProjectileBatteryAmmoProvider
    proto: FireBallFlamethrower
    fireCost: 50
  - type: Gun
    maxAngle: 60
    minAngle: 30
    fireRate: 0.5
    useKey: false
    selectedMode: SemiAuto
    availableModes:
    - SemiAuto
    soundGunshot: /Audio/Magic/fireball.ogg 

#лавовый краб
- type: entity
  id: MobLavaCrabLavaLand
  name: магматитовый краб
  suffix: LavaLand
  description: Такой красивый, такой опасный.
  parent: [ MobOreCrab, BaseMobLavaLand ]
  components:
  - type: Sprite
    sprite: Adventure/Roles/LavaLand/mobs/lavacrab.rsi
    layers:
    - map: [ "enum.DamageStateVisualLayers.Base" ]
      state: alive
    - map: [ "enum.DamageStateVisualLayers.BaseUnshaded" ]
      state: light_alive
      shader: unshaded
  - type: DamageStateVisuals
    states:
      Alive:
        Base: alive
        BaseUnshaded: light_alive
  - type: MobThresholds
    thresholds:
      0: Alive
      50: Dead
  - type: HTN
    rootTask:
      task: SimpleHostileCompound
  - type: MeleeWeapon
    hidden: true
    soundHit:
      path: /Audio/Weapons/Xeno/alien_claw_flesh3.ogg
    damage:
      types:
        Blunt: 5
  - type: MovementSpeedModifier
    baseWalkSpeed : 2
    baseSprintSpeed : 2.5
  - type: NpcFactionMember
    factions:
      - SimpleHostile
  - type: Damageable
    damageContainer: StructuralInorganic
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 50
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: GlassBreak
      - !type:SpawnEntitiesBehavior
        spawn:
          Coal1:
            min: 2
            max: 4
          MaterialMagmatiteFragment1:
            min: 0
            max: 1
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
      - !type:ExplodeBehavior
  - type: PointLight
    radius: 2
    energy: 1.5
    color: "#f2511e"
  - type: AmbientSound
    range: 10
    sound:
      path: /Audio/Adventure/LavaLand/Magma.ogg
  - type: ExplosionResistance
    damageCoefficient: 0.0
  - type: Explosive
    explosionType: Default
    totalIntensity: 5
    intensitySlope: 1
    maxIntensity: 3
    canCreateVacuum: false
    deleteAfterExplosion: false
  - type: Tag
    tags:
    - CannotSuicide
    - FootstepSound  
    - LavaMob

#легион
- type: entity
  id: MobLavaLandLegion
  parent: BaseMobLavaLand
  suffix: LavaLand
  name: легион
  description: Головастый парень.
  components:
  - type: Tag
    tags:
    - CannotSuicide
    - FootstepSound 
    - LavaMob
  - type: Sprite
    sprite: Adventure/Roles/LavaLand/mobs/legions/legion.rsi
  - type: MovementSpeedModifier
    baseWalkSpeed : 2.0
    baseSprintSpeed : 2.0
  - type: MobThresholds
    thresholds:
      0: Alive
      75: Dead
  - type: MeleeWeapon
    soundHit:
      path: "/Audio/Weapons/smash.ogg"
    angle: 0
    attackRate: 0.75
    animation: WeaponArcPunch
    damage:
      types:
        Slash: 5
  - type: Butcherable
    butcherDelay: 5
    spawned:
    - id: SalvageHumanCorpse
      amount: 1
    - id: FoodLegionHeart
      amount: 1
    - id: Coal1
      amount: 2
    - id: MaterialMagmatiteFragment1
      amount: 1
  - type: Gun
    fireRate: 1
    selectedMode: SemiAuto
    showExamineText: false
    availableModes:
    - SemiAuto
    soundGunshot: null
  - type: RechargeBasicEntityAmmo
    showExamineText: false
    rechargeCooldown: 5
    rechargeSound: null
  - type: BasicEntityAmmoProvider
    proto: MobLavaLandLegionSkull
    capacity: 1
    count: 1
  - type: HTN
    rootTask:
      task: SimpleRangedHostileCompound
    blackboard:
      VisionRadius: !type:Single
        9
      AggroVisionRadius: !type:Single
        9
  - type: AmbientSound
    range: 5
    sound:
      path: /Audio/Adventure/LavaLand/legion_whispers.ogg 

- type: entity
  id: MobLavaLandLegionSkull
  parent: [ MobHivelordBrood, BaseMobLavaLand ]
  name: череп легиона
  categories: [ HideSpawnMenu ]
  suffix: LavaLand
  description: Чуть менее головастый парень.
  components:
  - type: Sprite
    sprite: Adventure/Roles/LavaLand/mobs/legions/legionSkull.rsi
    layers:
    - map: [ "enum.DamageStateVisualLayers.Base" ]
      state: alive
    - map: [ "enum.DamageStateVisualLayers.BaseUnshaded" ]
      state: light_alive
      shader: unshaded
  - type: DamageStateVisuals
    states:
      Alive:
        Base: alive
        BaseUnshaded: light_alive
  - type: MovementSpeedModifier
    baseWalkSpeed : 3.5
    baseSprintSpeed : 4.0
  - type: MobThresholds
    thresholds:
      0: Alive
      5: Dead
  - type: MeleeWeapon
    soundHit:
      path: /Audio/Weapons/bladeslice.ogg
    angle: 0
    attackRate: 1.0
    range: 0.75
    animation: WeaponArcPunch
    damage:
      types:
        Slash: 5
  - type: AmbientSound
    range: 5
    sound:
      path: /Audio/Adventure/LavaLand/legion_whispers.ogg 

- type: entity
  id: FoodLegionHeart
  parent: FoodBase
  categories: [ HideSpawnMenu ]
  suffix: LavaLand
  name: сердце легиона
  description: Каменное цердце, обладающее целебными свойствами.
  components:
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 5
        reagents:
        - ReagentId: Rororium
          Quantity: 5
  - type: Sprite
    sprite: Adventure/Roles/LavaLand/materials/gems.rsi
    state: core1
  - type: Item
    size: Normal
  - type: Perishable
    rotAfter: 120 
    molsPerSecondPerUnitMass: 0
    forceRotProgression: true
  - type: RotInto
    entity: FoodLegionHeartDead
    stage: 1
  - type: Tag
    tags:
    - Meat
    - ClothMade

- type: entity
  id: FoodLegionHeartDead
  parent: BaseItem
  categories: [ HideSpawnMenu ]
  suffix: LavaLand
  name: потухшее сердце легиона
  description: Оно потухло и утратило свои свойства.
  components:
  - type: Sprite
    sprite: Adventure/Roles/LavaLand/materials/gems.rsi
    state: core2
  - type: SpaceGarbage
  - type: Item
    size: Normal
  - type: StaticPrice
    price: 500

#Рудожор
- type: entity
  id: MobLavaLandGoldWarm
  parent: BaseMobLavaLand
  suffix: LavaLand
  name: рудожор
  description: Преувеличенно толстый червяк золотистого цвета
  components:
  - type: Sprite
    sprite: Adventure/Roles/LavaLand/mobs/gold_warm.rsi
    layers:
    - map: [ "enum.DamageStateVisualLayers.Base" ]
      state: alive
  - type: DamageStateVisuals
    states:
      Alive:
        Base: alive
      Dead:
        Base: dead
  - type: MovementSpeedModifier
    baseWalkSpeed : 2.00
    baseSprintSpeed : 2.00
  - type: MobThresholds
    thresholds:
      0: Alive
      100: Dead
  - type: MeleeWeapon
    soundHit:
      path: "/Audio/Weapons/smash.ogg"
    angle: 0
    attackRate: 0.75
    animation: WeaponArcPunch
    damage:
      types:
        Slash: 10
        Piercing: 5
  - type: Butcherable
    spawned:
    - id: OreRupee1
      amount: 1
    - id: GoldOre1
      amount: 3
    - id: SpawnOreGemRandom
      amount: 3
  - type: Tag
    tags:
    - CannotSuicide
    - FootstepSound  
    - LavaMob
  - type: FootstepModifier
    footstepSoundCollection:
      collection: LarvaRun
      params: 
        volume: -1
  - type: HTN
    rootTask:
      task: SimpleHostileCompound
    blackboard: 
      VisionRadius: !type:Single
        15
      AggroVisionRadius: !type:Single
        15

#Антиабуз
- type: entity
  id: MobLavaLandGoliathEmpty
  parent: MobLavaLandGoliath
  categories: [ HideSpawnMenu ]
  components:
  - type: Butcherable
    spawned:
    - id: FoodMeatGoliath
      amount: 3
    - id: Coal1
      amount: 3

- type: entity
  id: MobLavaLandLegionEmpty
  parent: MobLavaLandLegion
  categories: [ HideSpawnMenu ]
  components:
  - type: Butcherable
    butcherDelay: 5
    spawned:
    - id: Coal1
      amount: 3

- type: entity
  id: MobWatcherLavaLandFireEmpty
  parent: MobWatcherLavaLandFire
  categories: [ HideSpawnMenu ]
  components:
  - type: Butcherable
    spawned:
    - id: Coal1
      amount: 3