- type: dungeonConfig
  id: AdventureLava
  layers:
    - !type:PrototypeDunGen
      proto: LavaBlob
    - !type:PrototypeDunGen
      proto: LavaSmallPaths
      inheritDungeons: All
#Rooms
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker1
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker2
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker3
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker4
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker5
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker6
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker7
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker8
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker9
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker10
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker11
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker12
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker13
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker14
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker15
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker16
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker17
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker18
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker19
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker20
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker21
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker22
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker23
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker24
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker25
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker26
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker27
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker28
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker29
    - !type:EntityTableDunGen
      minCount: 1
      maxCount: 1
      table:
        id: LavalendRoomMarker30
#Rooms
    - !type:PrototypeDunGen
      proto: LavaFill
      inheritDungeons: All
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: WallRockBasaltBananium
      count: 20
      minGroupSize: 3
      maxGroupSize: 8
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: WallRockBasaltTin
      count: 30
      minGroupSize: 8
      maxGroupSize: 12
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: WallRockBasaltCoal
      count: 30
      minGroupSize: 8
      maxGroupSize: 12
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: WallRockBasaltQuartz
      count: 30
      minGroupSize: 10
      maxGroupSize: 15
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: WallRockBasaltSalt
      count: 30
      minGroupSize: 8
      maxGroupSize: 12
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: WallRockBasaltGold
      count: 30
      minGroupSize: 8
      maxGroupSize: 12
    - !type:OreDunGen
      replacement: WallRockBasaltGold
      entity: WallRockBasaltGoldWarm
      count: 20
      minGroupSize: 2
      maxGroupSize: 5
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: WallRockBasaltSilver
      count: 30
      minGroupSize: 8
      maxGroupSize: 12
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: WallRockBasaltPlasma
      count: 30
      minGroupSize: 4
      maxGroupSize: 8
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: WallRockBasaltUranium
      count: 30
      minGroupSize: 4
      maxGroupSize: 8
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: WallRockBasaltArtifactFragment
      count: 20
      minGroupSize: 1
      maxGroupSize: 3
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: WallRockBasaltDiamond
      count: 10
      minGroupSize: 1
      maxGroupSize: 2
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: WallRockBasaltMagmatite
      count: 30
      minGroupSize: 15
      maxGroupSize: 30
    - !type:OreDunGen
      replacement: WallRockBasaltMagmatite
      entity: WallRockBasaltMagmatiteCrab
      count: 10
      minGroupSize: 2
      maxGroupSize: 5
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: WallRockBasaltGem
      count: 15
      minGroupSize: 3
      maxGroupSize: 6
    - !type:OreDunGen
      replacement: WallRockBasaltMagmatite
      entity: FloorLavaEntity
      count: 50
      minGroupSize: 8
      maxGroupSize: 15
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: BasaltRandomLava
      count: 350
      minGroupSize: 3
      maxGroupSize: 10
    - !type:OreDunGen
      replacement: BasaltRandomLava
      entity: NecroSpike
      count: 30
      minGroupSize: 1
      maxGroupSize: 1
    - !type:OreDunGen
      replacement: BasaltRandomLava
      entity: CoalMushroom
      count: 20
      minGroupSize: 1
      maxGroupSize: 3
    - !type:OreDunGen
      replacement: BasaltRandomLava
      entity: PorciniMushroom
      count: 20
      minGroupSize: 1
      maxGroupSize: 3
    - !type:OreDunGen
      replacement: BasaltRandomLava
      entity: InocybeMushroom
      count: 20
      minGroupSize: 1
      maxGroupSize: 3
    - !type:OreDunGen
      replacement: BasaltRandomLava
      entity: PolyporeMushroom
      count: 20
      minGroupSize: 1
      maxGroupSize: 3
    - !type:OreDunGen
      replacement: BasaltRandomLava
      entity: SpaceCactus
      count: 20
      minGroupSize: 1
      maxGroupSize: 3
    - !type:OreDunGen
      replacement: WallRockBasalt
      entity: WallRockBasaltLavaland
      count: 70
      minGroupSize: 15
      maxGroupSize: 35
    - !type:OreDunGen
      replacement: WallRockBasaltLavaland
      entity: WallRockBasaltGibtonite
      count: 15
      minGroupSize: 1
      maxGroupSize: 1

- type: dungeonConfig
  id: LavaBlob
  layers:
  - !type:NoiseDistanceDunGen
    size: 272, 272
    distanceConfig: !type:DunGenEuclideanSquaredDistance
      blendWeight: 0.80
    layers:
    - tile: FloorBasaltLavaLand
      threshold: 0.50
      noise:
        frequency: 0.010
        noiseType: OpenSimplex2
        fractalType: FBm
        octaves: 5
        lacunarity: 2
        gain: 0.5

- type: dungeonConfig
  id: LavaSmallPaths
  reserveTiles: true
  layers:
  - !type:ReplaceTileDunGen
    layers:
    - tile: FloorBasaltLavaLand
      threshold: 0.75
      noise:
        frequency: 0.040
        noiseType: OpenSimplex2
        fractalType: Ridged
        lacunarity: 1.5
        octaves: 2
        gain: 2.0
  - !type:MobsDunGen
    minCount: 30
    maxCount: 40
    contents: LavaLandSmallPathsMobs

- type: entityTable
  id: LavaLandSmallPathsMobs
  table: !type:GroupSelector
    children:
    - id: SalvageSpawnerMobLavaLand
      amount: 1

- type: dungeonConfig
  id: LavaFill
  layers:
  - !type:FillGridDunGen
    entity: WallRockBasalt
    allowedTiles:
    - FloorBasaltLavaLand

#спавнеры мобов
- type: entity
  parent: MarkerBase
  id: SalvageSpawnerMobLavaLand
  name: Mining Lava Mob Spawner
  components:
  - type: Sprite
    layers:
    - state: green
    - sprite: Mobs/Aliens/Asteroid/goliath.rsi
      state: goliath
  - type: EntityTableSpawner
    table: !type:GroupSelector
      children:
      - id: MobLavaLandGoliath
        weight: 20
      - id: MobLavaLandGoliathAncient
        weight: 15
      - id: MobWatcherLavaLandFire
        weight: 20
      - id: MobLavaLandLegion
        weight: 30
      - id: MobSkeletonBloodMinerCutter
        weight: 5
      - id: MobSkeletonBloodMinerAccelerator
        weight: 5
      - id: MobSkeletonBloodMinerMiningDrill
        weight: 5

- type: tile
  id: FloorBasaltLavaLand
  parent: FloorBasalt
  name: пол базальт

- type: localizedDataset
  id: LavaName
  values:
    prefix: names-lavaland-dataset-
    count: 1

- type: entity
  id: BasaltRandomLava
  parent: BasaltOne
  suffix: Рандомный лавалендский, так надо карочи.
  components:
    - type: RandomSprite
      available:
        - 0:
            basalt1: ""
            basalt2: ""
            basalt3: ""
            basalt4: ""
            basalt5: ""

- type: entity
  id: WallRockBasaltLavaland
  name: базальт
  suffix: базальт LavaLand
  description: Удерживает воздух внутри, а ассистентов снаружи.
  parent: WallRock
  components:
  - type: Icon
    sprite: Structures/Walls/rock.rsi
    state: rock_wall
  - type: Sprite
    sprite: Structures/Walls/rock.rsi
    layers:
    - state: rock_wall
    - map: [ "enum.EdgeLayer.South" ]
      state: rock_wall_south
    - map: [ "enum.EdgeLayer.East" ]
      state: rock_wall_east
    - map: [ "enum.EdgeLayer.North" ]
      state: rock_wall_north
    - map: [ "enum.EdgeLayer.West" ]
      state: rock_wall_west

- type: entity
  id: WallRockBasaltGibtonite
  name: базальт
  description: Удерживает воздух внутри, а ассистентов снаружи.
  parent: [ BaseRockGibtonite, AsteroidRock ]
  suffix: Гибтонит LavaLand
  components:
    - type: Sprite
      layers:
        - state: rock_wall
        - map: [ "enum.EdgeLayer.South" ]
          state: rock_wall_south
        - map: [ "enum.EdgeLayer.East" ]
          state: rock_wall_east
        - map: [ "enum.EdgeLayer.North" ]
          state: rock_wall_north
        - map: [ "enum.EdgeLayer.West" ]
          state: rock_wall_west
        - state: gibtonite_inactive
          visible: false
          map: [ "enum.MiningScannerVisualLayers.Overlay", "gib" ]
    - type: RandomTimerTrigger
      min: 2
      max: 5
    - type: Explosive
      explosionType: DemolitionCharge
      totalIntensity: 200
      intensitySlope: 3
      maxIntensity: 10
      canCreateVacuum: false
    - type: Destructible
      thresholds:
      - trigger:
          !type:DamageTrigger
          damage: 3
        behaviors:
        - !type:TimerStartBehavior
        - !type:PlaySoundBehavior
          sound:
            collection: GlassBreak
      - trigger:
          !type:DamageTrigger
          damage: 1000
        behaviors:
        - !type:DoActsBehavior
          acts: ["Destruction"]
        - !type:TriggerBehavior
