#1
- type: dungeonRoom
  id: LavalendMarkerRooms
  size: 11,11
  atlas: /Maps/Adventure/LavaLand/AmirMaps.yml
  offset: 0,0
  ignoreTile: FloorShuttleOrange
  tags:
  - Lavalend1

- type: Tag
  id: Lavalend1

- type: entity
  id: LavalendRoomMarker1
  parent: BaseRoomMarker
  name: Рандом комната Лаваленда
  components:
  - type: RoomFill
    minSize: 10,10
    maxSize: 50,50
    roomWhitelist:
      tags:
      - Lavalend1

#2
- type: dungeonRoom
  id: LavalendMarkerRoomsA
  size: 11,11
  atlas: /Maps/Adventure/LavaLand/AmirMaps.yml
  offset: 12,0
  ignoreTile: FloorShuttleOrange
  tags:
  - Lavalend2

- type: Tag
  id: Lavalend2

- type: entity
  id: LavalendRoomMarker2
  parent: BaseRoomMarker
  name: Рандом комната Лаваленда
  components:
  - type: RoomFill
    minSize: 10,10
    maxSize: 50,50
    roomWhitelist:
      tags:
      - Lavalend2

#3
- type: dungeonRoom
  id: LavalendMarkerRoomsB
  size: 11,11
  atlas: /Maps/Adventure/LavaLand/AmirMaps.yml
  offset: 24,0
  ignoreTile: FloorShuttleOrange
  tags:
  - Lavalend3

- type: Tag
  id: Lavalend3

- type: entity
  id: LavalendRoomMarker3
  parent: BaseRoomMarker
  name: Рандом комната Лаваленда
  components:
  - type: RoomFill
    minSize: 10,10
    maxSize: 50,50
    roomWhitelist:
      tags:
      - Lavalend3

#4
- type: dungeonRoom
  id: LavalendMarkerRoomsC
  size: 11,11
  atlas: /Maps/Adventure/LavaLand/AmirMaps.yml
  offset: 36,0
  ignoreTile: FloorShuttleOrange
  tags:
  - Lavalend4

- type: Tag
  id: Lavalend4

- type: entity
  id: LavalendRoomMarker4
  parent: BaseRoomMarker
  name: Рандом комната Лаваленда
  components:
  - type: RoomFill
    minSize: 10,10
    maxSize: 50,50
    roomWhitelist:
      tags:
      - Lavalend4

#5
- type: dungeonRoom
  id: LavalendMarkerRoomsF
  size: 11,11
  atlas: /Maps/Adventure/LavaLand/AmirMaps.yml
  offset: 0,12
  ignoreTile: FloorShuttleOrange
  tags:
  - Lavalend5

- type: Tag
  id: Lavalend5

- type: entity
  id: LavalendRoomMarker5
  parent: BaseRoomMarker
  name: Рандом комната Лаваленда
  components:
  - type: RoomFill
    minSize: 10,10
    maxSize: 50,50
    roomWhitelist:
      tags:
      - Lavalend5

#6
- type: dungeonRoom
  id: LavalendMarkerRoomsT
  size: 11,11
  atlas: /Maps/Adventure/LavaLand/AmirMaps.yml
  offset: 12,12
  ignoreTile: FloorShuttleOrange
  tags:
  - Lavalend6

- type: Tag
  id: Lavalend6

- type: entity
  id: LavalendRoomMarker6
  parent: BaseRoomMarker
  name: Рандом комната Лаваленда
  components:
  - type: RoomFill
    minSize: 10,10
    maxSize: 50,50
    roomWhitelist:
      tags:
      - Lavalend6

#7
- type: dungeonRoom
  id: LavalendMarkerRoomsU
  size: 11,11
  atlas: /Maps/Adventure/LavaLand/AmirMaps.yml
  offset: 24,12
  ignoreTile: FloorShuttleOrange
  tags:
  - Lavalend7

- type: Tag
  id: Lavalend7

- type: entity
  id: LavalendRoomMarker7
  parent: BaseRoomMarker
  name: Рандом комната Лаваленда
  components:
  - type: RoomFill
    minSize: 10,10
    maxSize: 50,50
    roomWhitelist:
      tags:
      - Lavalend7

#8
- type: dungeonRoom
  id: LavalendMarkerRoomsD
  size: 11,11
  atlas: /Maps/Adventure/LavaLand/AmirMaps.yml
  offset: 36,12
  ignoreTile: FloorShuttleOrange
  tags:
  - Lavalend8

- type: Tag
  id: Lavalend8

- type: entity
  id: LavalendRoomMarker8
  parent: BaseRoomMarker
  name: Рандом комната Лаваленда
  components:
  - type: RoomFill
    minSize: 10,10
    maxSize: 50,50
    roomWhitelist:
      tags:
      - Lavalend8

#9
- type: dungeonRoom
  id: LavalendMarkerRoomsN
  size: 11,11
  atlas: /Maps/Adventure/LavaLand/AmirMaps.yml
  offset: 0,24
  ignoreTile: FloorShuttleOrange
  tags:
  - Lavalend9

- type: Tag
  id: Lavalend9

- type: entity
  id: LavalendRoomMarker9
  parent: BaseRoomMarker
  name: Рандом комната Лаваленда
  components:
  - type: RoomFill
    minSize: 10,10
    maxSize: 50,50
    roomWhitelist:
      tags:
      - Lavalend9

#10
- type: dungeonRoom
  id: LavalendMarkerRoomsW
  size: 11,11
  atlas: /Maps/Adventure/LavaLand/AmirMaps.yml
  offset: 12,24
  ignoreTile: FloorShuttleOrange
  tags:
  - Lavalend10

- type: Tag
  id: Lavalend10

- type: entity
  id: LavalendRoomMarker10
  parent: BaseRoomMarker
  name: Рандом комната Лаваленда
  components:
  - type: RoomFill
    minSize: 10,10
    maxSize: 50,50
    roomWhitelist:
      tags:
      - Lavalend10

#11
- type: dungeonRoom
  id: LavalendMarkerRoomsV
  size: 11,11
  atlas: /Maps/Adventure/LavaLand/AmirMaps.yml
  offset: 24,24
  ignoreTile: FloorShuttleOrange
  tags:
  - Lavalend11

- type: Tag
  id: Lavalend11

- type: entity
  id: LavalendRoomMarker11
  parent: BaseRoomMarker
  name: Рандом комната Лаваленда
  components:
  - type: RoomFill
    minSize: 10,10
    maxSize: 50,50
    roomWhitelist:
      tags:
      - Lavalend11

#12
- type: dungeonRoom
  id: LavalendMarkerRoomsS
  size: 11,11
  atlas: /Maps/Adventure/LavaLand/AmirMaps.yml
  offset: 36,24
  ignoreTile: FloorShuttleOrange
  tags:
  - Lavalend12

- type: Tag
  id: Lavalend12

- type: entity
  id: LavalendRoomMarker12
  parent: BaseRoomMarker
  name: Рандом комната Лаваленда
  components:
  - type: RoomFill
    minSize: 10,10
    maxSize: 50,50
    roomWhitelist:
      tags:
      - Lavalend12

#13
- type: dungeonRoom
  id: LavalendMarkerRoomsI
  size: 11,11
  atlas: /Maps/Adventure/LavaLand/AmirMaps.yml
  offset: 0,36
  ignoreTile: FloorShuttleOrange
  tags:
  - Lavalend13

- type: Tag
  id: Lavalend13

- type: entity
  id: LavalendRoomMarker13
  parent: BaseRoomMarker
  name: Рандом комната Лаваленда
  components:
  - type: RoomFill
    minSize: 10,10
    maxSize: 50,50
    roomWhitelist:
      tags:
      - Lavalend13

#14
- type: dungeonRoom
  id: LavalendMarkerRoomsP
  size: 11,11
  atlas: /Maps/Adventure/LavaLand/AmirMaps.yml
  offset: 12,36
  ignoreTile: FloorShuttleOrange
  tags:
  - Lavalend14

- type: Tag
  id: Lavalend14

- type: entity
  id: LavalendRoomMarker14
  parent: BaseRoomMarker
  name: Рандом комната Лаваленда
  components:
  - type: RoomFill
    minSize: 10,10
    maxSize: 50,50
    roomWhitelist:
      tags:
      - Lavalend14

#15
- type: dungeonRoom
  id: LavalendMarkerRoomsG
  size: 11,11
  atlas: /Maps/Adventure/LavaLand/AmirMaps.yml
  offset: 24,36
  ignoreTile: FloorShuttleOrange
  tags:
  - Lavalend15

- type: Tag
  id: Lavalend15

- type: entity
  id: LavalendRoomMarker15
  parent: BaseRoomMarker
  name: Рандом комната Лаваленда
  components:
  - type: RoomFill
    minSize: 10,10
    maxSize: 50,50
    roomWhitelist:
      tags:
      - Lavalend15

#16
- type: dungeonRoom
  id: LavalendMarkerRoomsK
  size: 11,11
  atlas: /Maps/Adventure/LavaLand/AmirMaps.yml
  offset: 36,36
  ignoreTile: FloorShuttleOrange
  tags:
  - Lavalend16

- type: Tag
  id: Lavalend16

- type: entity
  id: LavalendRoomMarker16
  parent: BaseRoomMarker
  name: Рандом комната Лаваленда
  components:
  - type: RoomFill
    minSize: 10,10
    maxSize: 50,50
    roomWhitelist:
      tags:
      - Lavalend16

#17
- type: dungeonRoom
  id: LavalendMarkerRoomsAA
  size: 11,11
  atlas: /Maps/Adventure/LavaLand/BorkMaps.yml
  offset: 0,0
  ignoreTile: FloorShuttleOrange
  tags:
  - Lavalend17

- type: Tag
  id: Lavalend17

- type: entity
  id: LavalendRoomMarker17
  parent: BaseRoomMarker
  name: Рандом комната Лаваленда
  components:
  - type: RoomFill
    minSize: 10,10
    maxSize: 50,50
    roomWhitelist:
      tags:
      - Lavalend17

#18
- type: dungeonRoom
  id: LavalendMarkerRoomsAAA
  size: 11,11
  atlas: /Maps/Adventure/LavaLand/BorkMaps.yml
  offset: 12,0
  ignoreTile: FloorShuttleOrange
  tags:
  - Lavalend18

- type: Tag
  id: Lavalend18

- type: entity
  id: LavalendRoomMarker18
  parent: BaseRoomMarker
  name: Рандом комната Лаваленда
  components:
  - type: RoomFill
    minSize: 10,10
    maxSize: 50,50
    roomWhitelist:
      tags:
      - Lavalend18

#19
- type: dungeonRoom
  id: LavalendMarkerRoomsBB
  size: 11,11
  atlas: /Maps/Adventure/LavaLand/BorkMaps.yml
  offset: 24,0
  ignoreTile: FloorShuttleOrange
  tags:
  - Lavalend19

- type: Tag
  id: Lavalend19

- type: entity
  id: LavalendRoomMarker19
  parent: BaseRoomMarker
  name: Рандом комната Лаваленда
  components:
  - type: RoomFill
    minSize: 10,10
    maxSize: 50,50
    roomWhitelist:
      tags:
      - Lavalend19

#20
- type: dungeonRoom
  id: LavalendMarkerRoomsCC
  size: 11,11
  atlas: /Maps/Adventure/LavaLand/BorkMaps.yml
  offset: 36,0
  ignoreTile: FloorShuttleOrange
  tags:
  - Lavalend20

- type: Tag
  id: Lavalend20

- type: entity
  id: LavalendRoomMarker20
  parent: BaseRoomMarker
  name: Рандом комната Лаваленда
  components:
  - type: RoomFill
    minSize: 10,10
    maxSize: 50,50
    roomWhitelist:
      tags:
      - Lavalend20

#21
- type: dungeonRoom
  id: LavalendMarkerRoomsUU
  size: 11,11
  atlas: /Maps/Adventure/LavaLand/BorkMaps.yml
  offset: 24,12
  ignoreTile: FloorShuttleOrange
  tags:
  - Lavalend21

- type: Tag
  id: Lavalend21

- type: entity
  id: LavalendRoomMarker21
  parent: BaseRoomMarker
  name: Рандом комната Лаваленда
  components:
  - type: RoomFill
    minSize: 10,10
    maxSize: 50,50
    roomWhitelist:
      tags:
      - Lavalend21

#22
- type: dungeonRoom
  id: LavalendMarkerRoomsDD
  size: 11,11
  atlas: /Maps/Adventure/LavaLand/BorkMaps.yml
  offset: 36,12
  ignoreTile: FloorShuttleOrange
  tags:
  - Lavalend22

- type: Tag
  id: Lavalend22

- type: entity
  id: LavalendRoomMarker22
  parent: BaseRoomMarker
  name: Рандом комната Лаваленда
  components:
  - type: RoomFill
    minSize: 10,10
    maxSize: 50,50
    roomWhitelist:
      tags:
      - Lavalend22

#23
- type: dungeonRoom
  id: LavalendMarkerRoomsMaze
  size: 23,23
  atlas: /Maps/Adventure/LavaLand/BorkMaps.yml
  offset: 0,12
  ignoreTile: FloorShuttleOrange
  tags:
  - Lavalend23

- type: Tag
  id: Lavalend23

- type: entity
  id: LavalendRoomMarker23
  parent: BaseRoomMarker
  name: Рандом комната Лаваленда
  components:
  - type: RoomFill
    minSize: 10,10
    maxSize: 50,50
    roomWhitelist:
      tags:
      - Lavalend23

#24
- type: dungeonRoom
  id: LavalendMarkerRoomsMinePost
  size: 23,23
  atlas: /Maps/Adventure/LavaLand/BorkMaps.yml
  offset: 0,36
  ignoreTile: FloorShuttleOrange
  tags:
  - Lavalend24

- type: Tag
  id: Lavalend24

- type: entity
  id: LavalendRoomMarker24
  parent: BaseRoomMarker
  name: Рандом комната Лаваленда
  components:
  - type: RoomFill
    minSize: 10,10
    maxSize: 50,50
    roomWhitelist:
      tags:
      - Lavalend24

#25
- type: dungeonRoom
  id: LavalendMarkerRoomsDragon
  size: 17,17
  atlas: /Maps/Adventure/LavaLand/AmirMaps.yml
  offset: 0,48
  ignoreTile: FloorShuttleOrange
  tags:
  - Lavalend25

- type: Tag
  id: Lavalend25

- type: entity
  id: LavalendRoomMarker25
  parent: BaseRoomMarker
  name: Рандом комната Лаваленда
  components:
  - type: RoomFill
    minSize: 10,10
    maxSize: 50,50
    roomWhitelist:
      tags:
      - Lavalend25

#26
- type: dungeonRoom
  id: LavalendMarkerRoomsColoss
  size: 17,17
  atlas: /Maps/Adventure/LavaLand/AmirMaps.yml
  offset: 18,48
  ignoreTile: FloorShuttleOrange
  tags:
  - Lavalend26

- type: Tag
  id: Lavalend26

- type: entity
  id: LavalendRoomMarker26
  parent: BaseRoomMarker
  name: Рандом комната Лаваленда
  components:
  - type: RoomFill
    minSize: 10,10
    maxSize: 50,50
    roomWhitelist:
      tags:
      - Lavalend26

#27
- type: dungeonRoom
  id: LavalendMarkerRoomsLegion
  size: 17,17
  atlas: /Maps/Adventure/LavaLand/AmirMaps.yml
  offset: 36,48
  ignoreTile: FloorShuttleOrange
  tags:
  - Lavalend27

- type: Tag
  id: Lavalend27

- type: entity
  id: LavalendRoomMarker27
  parent: BaseRoomMarker
  name: Рандом комната Лаваленда
  components:
  - type: RoomFill
    minSize: 10,10
    maxSize: 50,50
    roomWhitelist:
      tags:
      - Lavalend27