- type: antag
  id: InitialInfected
  name: roles-antag-initial-infected-name
  antagonist: true
  setPreference: true
  objective: roles-antag-initial-infected-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 36000 #10 hrs # Adventure
# Adventure-edit-start
  - !type:SpeciesRequirement
    inverted: true
    species:
    - Synth
# Adventure-edit-end
  guides: [ Zombies ]

- type: antag
  id: Zombie
  name: roles-antag-zombie-name
  antagonist: true
  setPreference: false
  objective: roles-antag-zombie-objective
  guides: [ Zombies ]
